sudo: required
dist: focal
language: python
matrix:
  include:
    - python: 3.7
      TOXENV: py37
    - python: 3.8
      TOXENV: py38
    - python: 3.7
      TOXENV: lint
services:
  - redis-server
install:
  - pip install -U pip
  - pip install tox
script: tox
notifications:
  slack: onaio:snkNXgprD498qQv4DgRREKJF