sudo: required
dist: focal
language: python
jobs:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.7
      env: TOXENV=lint
services:
  - redis-server
install:
  - pip install -U pip
  - pip install tox
script: tox
notifications:
  slack: onaio:snkNXgprD498qQv4DgRREKJF