version: "3"

services:
  cache:
    image: redis:6-alpine
  db:
    image: postgres:13
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U duva"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=duva
      - POSTGRES_USER=duva
      - POSTGRES_DB=duva
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: duva:latest
    stdin_open: true
    tty: true
    command: ["/start-reload.sh"]
    volumes:
      # For local development
      - .:/app
      - ~/.aws:/root/.aws
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      - REDIS_URL=redis://cache
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_DB=1
      - DEBUG=True
      - POSTGRES_SERVER=db
      - POSTGRES_USER=duva
      - POSTGRES_PASSWORD=duva
      - POSTGRES_DB=duva
      - SECRET_KEY=0DHasftEjNSzVz3hD42aPxJKYJpSVKr86IQhAeBRmp4=
      - S3_BUCKET=hypermind-mvp
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: duva:latest
    command: "bash init_scheduler.sh"
    volumes:
      # For local development
      - .:/app
      - ~/.aws:/root/.aws
    depends_on:
      - cache
      - db
    environment:
      - REDIS_URL=redis://cache
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_DB=1
      - DEBUG=True
      - POSTGRES_SERVER=db
      - POSTGRES_USER=duva
      - POSTGRES_PASSWORD=duva
      - POSTGRES_DB=duva
      - SECRET_KEY=0DHasftEjNSzVz3hD42aPxJKYJpSVKr86IQhAeBRmp4=
      - S3_BUCKET=hypermind-mvp
      - QUEUE_NAME=default
      - CRON_SCHEDULE=*/30 * * * *
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: duva:latest
    command: "rq worker -c app.jobs.settings"
    volumes:
      # For local development
      - .:/app
      - ~/.aws:/root/.aws
    depends_on:
      - cache
      - db
    environment:
      - REDIS_URL=redis://cache
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_DB=1
      - DEBUG=True
      - POSTGRES_SERVER=db
      - POSTGRES_USER=duva
      - POSTGRES_PASSWORD=duva
      - POSTGRES_DB=duva
      - SECRET_KEY=0DHasftEjNSzVz3hD42aPxJKYJpSVKr86IQhAeBRmp4=
      - S3_BUCKET=hypermind-mvp
      - QUEUE_NAME=default
      - CRON_SCHEDULE=*/30 * * * *

volumes:
  database:
