"""Initial migration

Revision ID: 0b9ae1eb0b30
Revises:
Create Date: 2021-01-21 15:16:36.435591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0b9ae1eb0b30"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "server",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("client_secret", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("server", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["server"], ["server.id"], ondelete="CASCADE", name="user_server_fkey"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server", "username", name="_server_user_uc"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "configuration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_address", sa.String(), nullable=True),
        sa.Column("site_name", sa.String(), nullable=True),
        sa.Column("token_name", sa.String(), nullable=True),
        sa.Column("token_value", sa.String(), nullable=True),
        sa.Column("project_name", sa.String(), nullable=True),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "server_address",
            "token_name",
            "user",
            name="_server_token_name_uc",
        ),
    )
    op.create_index(op.f("ix_configuration_id"), "configuration", ["id"], unique=False)
    op.create_table(
        "hyper_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("last_synced", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("configuration_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["configuration_id"], ["configuration.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filename", name="hyper_file_filename_key"),
        sa.UniqueConstraint("user", "form_id", name="_user_form_id_uc"),
    )
    op.create_index(op.f("ix_hyper_file_id"), "hyper_file", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hyper_file_id"), table_name="hyper_file")
    op.drop_table("hyper_file")
    op.drop_index(op.f("ix_configuration_id"), table_name="configuration")
    op.drop_table("configuration")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_table("server")
    # ### end Alembic commands ###
