"""Change 'server' field to 'server_id'

Revision ID: 2b468eeb193d
Revises: e28d24caaf56
Create Date: 2021-07-01 10:28:35.759419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b468eeb193d"
down_revision = "e28d24caaf56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("server_id", sa.Integer(), nullable=True))
    op.drop_constraint("_server_user_uc", "user", type_="unique")
    op.create_unique_constraint("_server_user_uc", "user", ["server_id", "username"])
    op.drop_constraint(None, "user", type_="foreignkey")
    op.create_foreign_key(
        None, "user", "server", ["server_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("user", "server")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("server", sa.INTEGER(), nullable=True))
    op.drop_constraint(None, "user", type_="foreignkey")
    op.create_foreign_key(
        None, "user", "server", ["server"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("_server_user_uc", "user", type_="unique")
    op.create_unique_constraint("_server_user_uc", "user", ["server", "username"])
    op.drop_column("user", "server_id")
    # ### end Alembic commands ###
