"""Alter Hyper file filename field to be non-unique

Revision ID: 60383c2a9b44
Revises: 0b9ae1eb0b30
Create Date: 2021-02-12 16:44:45.035342

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "60383c2a9b44"
down_revision = "0b9ae1eb0b30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint("hyper_file_filename_key", "hyper_file")
    except NotImplementedError:
        with op.batch_alter_table("hyper_file", schema=None) as batch_op:
            batch_op.drop_constraint("hyper_file_filename_key")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("hyper_file_filename_key", "hyper_file", ["filename"])
    # ### end Alembic commands ###
