"""add access_token column

Revision ID: 7e33515949c2
Revises: dcbb9d699ca4
Create Date: 2023-06-08 10:10:58.240323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e33515949c2"
down_revision = "dcbb9d699ca4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "server", sa.Column("configuration", sa.JSON(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("access_token", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "access_token")
    op.drop_column("server", "configuration")
    # ### end Alembic commands ###
