"""Add file_status field

Revision ID: 8a3e2f1927b8
Revises: 60383c2a9b44
Create Date: 2021-02-23 11:30:23.732253

"""
import sqlalchemy as sa
from alembic import op

from app.models import ChoiceType, schemas

# revision identifiers, used by Alembic.
revision = "8a3e2f1927b8"
down_revision = "60383c2a9b44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hyper_file",
        sa.Column("file_status", ChoiceType(schemas.FileStatusEnum), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hyper_file", "file_status")
    # ### end Alembic commands ###
