"""Reorganize models

Revision ID: dcbb9d699ca4
Revises: 259f90f13bd6
Create Date: 2023-05-31 11:57:11.230587

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dcbb9d699ca4"
down_revision = "259f90f13bd6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hyper_file", "last_synced")
    op.create_index(op.f("ix_server_id"), "server", ["id"], unique=False)
    op.alter_column("configuration", "user", new_column_name="user_id")
    op.alter_column("hyper_file", "user", new_column_name="user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_server_id"), table_name="server")
    op.add_column(
        "hyper_file",
        sa.Column(
            "last_synced",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column("hyper_file", "user_id", new_column_name="user")
    op.alter_column("configuration", "user_id", new_column_name="user")
    # ### end Alembic commands ###
