"""Add meta_data field

Revision ID: e28d24caaf56
Revises: 8a3e2f1927b8
Create Date: 2021-04-19 16:42:54.162670

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e28d24caaf56"
down_revision = "8a3e2f1927b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hyper_file", sa.Column("meta_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hyper_file", "meta_data")
    # ### end Alembic commands ###
