name: CI Tests
on: [push, pull_request]
concurrency:
  group: ${{ github.head_ref }}-${{ github.event }}
  cancel-in-progress: true

jobs:
  github-actions-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.9
            toxenv: py39
          - python-version: 3.9
            toxenv: lint
          - python-version: 3.10
            toxenv: py310
          - python-version: 3.10
            toxenv: lint
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: duva
          POSTGRES_DB: duva
          POSTGRES_USER: duva
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install pip requirements
        run: |
          pip install -U pip
          pip install tox
      - name: Run tests
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
